#!/usr/bin/env sh
PKG_NAME=$(grep 'NAME=' $(dirname "$0")/info | cut -d= -f2)
PKG_DIR="$(cd "$(dirname "${0}")" && pwd)"

configure() {
	printf "[$PKG_NAME] Configuring...
[$PKG_NAME] Cloning into new directory...\n"

	git clone $(grep 'SYNC_URL=' $PKG_DIR/info | cut -d= -f2) $PKG_DIR/$PKG_NAME || { printf "[$PKG_NAME] Directory already here, checking for updates...\n"; cd $PKG_DIR/$PKG_NAME; git pull; cd ../; }

	if [[ $1 == 'y' ]]; then
		printf "[$PKG_NAME] Local install...\n"
		sed -i 's|PREFIX ?= .*|PREFIX ?= /home/'$(whoami)'/.local|' $PKG_DIR/$PKG_NAME/Makefile
		printf "[$PKG_NAME] Changed path to ~/.local/bin/...\n"
	else
		printf "[$PKG_NAME] Root install...\n"
		sed -i 's|PREFIX ?= .*|PREFIX ?= /opt|' $PKG_DIR/$PKG_NAME/Makefile
	fi
}

build() {
	cd $PKG_DIR/$PKG_NAME
	printf "[$PKG_NAME] Installing...\n"
	make install
	echo $PKG_NAME >> $PKG_DIR/../installed
}

uninstall() {
	cd $PKG_DIR/$PKG_NAME || { printf "[$PKG_NAME] Package is not installed.\n"; exit 1; }
	printf "[$PKG_NAME] Uninstalling...\n"
	make uninstall
	sed -i '/'$PKG_NAME'/d' $PKG_DIR/../installed
}

clean() {
	printf "[$PKG_NAME] Deleting work dir...\n"
	rm -rf $PKG_DIR/$PKG_NAME
}

"$@"
