#!/usr/bin/env sh
PKG_NAME=$(grep 'NAME=' $(dirname "$0")/info | cut -d= -f2)
configure() {
	printf "[$PKG_NAME] Configuring...
[$PKG_NAME] Cloning into new directory...\n"

	git clone $(grep 'SYNC_URL=' $(dirname "$0")/info | cut -d= -f2) $(dirname "$0")/$PKG_NAME || { printf "[$PKG_NAME] Directory aleady here, checking for updates...\n"; cd $PKG_NAME; git pull; cd ..; }

	if [[ $1 == 'y' ]]; then
		printf "[$PKG_NAME] Local install...\n"
		sed -i 's|PREFIX ?=.*|PREFIX ?= /home/'$(whoami)'/.local|' $(dirname "$0")/$PKG_NAME/Makefile
		printf "[$PKG_NAME] Changed path to ~/.local/bin/..."
	else
		printf "[$PKG_NAME] Root install..."
		sed -i 's|PREFIX ?=.*|PREFIX ?= /opt|' $(dirname "$0")/$PKG_NAME/Makefile
	fi
}

build() {
	cd $(dirname "$0")/$PKG_NAME
	printf "[$PKG_NAME] Installing..."
	make install
}

uninstall() {
	cd $(dirname "$0")/$PKG_NAME || { printf "[$PKG_NAME] Package is not installed."; exit 1; }
	printf "[$PKG_NAME] Uninstalling..."
	make uninstall
	cd ..
	rm -rf $PKG_NAME
}

"$@"
